package openfoodfacts

type OpenFoodFactCSVEntry struct {
	ID                                              string `bson:"_id" json:"_id"`
	AbbreviatedProductName                          string `json:"abbreviated_product_name,omitempty" csv:"abbreviated_product_name"`
	Acidity100g                                     string `json:"acidity_100g,omitempty" csv:"acidity_100g"`
	AddedSalt100g                                   string `json:"added-salt_100g,omitempty" csv:"added-salt_100g"`
	AddedSugars100g                                 string `json:"added-sugars_100g,omitempty" csv:"added-sugars_100g"`
	Additives                                       string `json:"additives,omitempty" csv:"additives"`
	AdditivesEn                                     string `json:"additives_en,omitempty" csv:"additives_en"`
	AdditivesN                                      string `json:"additives_n,omitempty" csv:"additives_n"`
	AdditivesTags                                   string `json:"additives_tags,omitempty" csv:"additives_tags"`
	Alcohol100g                                     string `json:"alcohol_100g,omitempty" csv:"alcohol_100g"`
	Allergens                                       string `json:"allergens,omitempty" csv:"allergens"`
	AllergensEn                                     string `json:"allergens_en,omitempty" csv:"allergens_en"`
	AlphaLinolenicAcid100g                          string `json:"alpha-linolenic-acid_100g,omitempty" csv:"alpha-linolenic-acid_100g"`
	ArachidicAcid100g                               string `json:"arachidic-acid_100g,omitempty" csv:"arachidic-acid_100g"`
	ArachidonicAcid100g                             string `json:"arachidonic-acid_100g,omitempty" csv:"arachidonic-acid_100g"`
	BehenicAcid100g                                 string `json:"behenic-acid_100g,omitempty" csv:"behenic-acid_100g"`
	BetaCarotene100g                                string `json:"beta-carotene_100g,omitempty" csv:"beta-carotene_100g"`
	BetaGlucan100g                                  string `json:"beta-glucan_100g,omitempty" csv:"beta-glucan_100g"`
	Bicarbonate100g                                 string `json:"bicarbonate_100g,omitempty" csv:"bicarbonate_100g"`
	Biotin100g                                      string `json:"biotin_100g,omitempty" csv:"biotin_100g"`
	BrandOwner                                      string `json:"brand_owner,omitempty" csv:"brand_owner"`
	Brands                                          string `json:"brands,omitempty" csv:"brands"`
	BrandsTags                                      string `json:"brands_tags,omitempty" csv:"brands_tags"`
	ButyricAcid100g                                 string `json:"butyric-acid_100g,omitempty" csv:"butyric-acid_100g"`
	Caffeine100g                                    string `json:"caffeine_100g,omitempty" csv:"caffeine_100g"`
	Calcium100g                                     string `json:"calcium_100g,omitempty" csv:"calcium_100g"`
	CapricAcid100g                                  string `json:"capric-acid_100g,omitempty" csv:"capric-acid_100g"`
	CaproicAcid100g                                 string `json:"caproic-acid_100g,omitempty" csv:"caproic-acid_100g"`
	CaprylicAcid100g                                string `json:"caprylic-acid_100g,omitempty" csv:"caprylic-acid_100g"`
	Carbohydrates100g                               string `json:"carbohydrates_100g,omitempty" csv:"carbohydrates_100g"`
	CarbonFootprintFromMeatOrFish100g               string `json:"carbon-footprint-from-meat-or-fish_100g,omitempty" csv:"carbon-footprint-from-meat-or-fish_100g"`
	CarbonFootprint100g                             string `json:"carbon-footprint_100g,omitempty" csv:"carbon-footprint_100g"`
	Carnitine100g                                   string `json:"carnitine_100g,omitempty" csv:"carnitine_100g"`
	Casein100g                                      string `json:"casein_100g,omitempty" csv:"casein_100g"`
	Categories                                      string `json:"categories,omitempty" csv:"categories"`
	CategoriesEn                                    string `json:"categories_en,omitempty" csv:"categories_en"`
	CategoriesTags                                  string `json:"categories_tags,omitempty" csv:"categories_tags"`
	CeroticAcid100g                                 string `json:"cerotic-acid_100g,omitempty" csv:"cerotic-acid_100g"`
	Chloride100g                                    string `json:"chloride_100g,omitempty" csv:"chloride_100g"`
	Chlorophyl100g                                  string `json:"chlorophyl_100g,omitempty" csv:"chlorophyl_100g"`
	Cholesterol100g                                 string `json:"cholesterol_100g,omitempty" csv:"cholesterol_100g"`
	Choline100g                                     string `json:"choline_100g,omitempty" csv:"choline_100g"`
	Chromium100g                                    string `json:"chromium_100g,omitempty" csv:"chromium_100g"`
	Cities                                          string `json:"cities,omitempty" csv:"cities"`
	CitiesTags                                      string `json:"cities_tags,omitempty" csv:"cities_tags"`
	Cocoa100g                                       string `json:"cocoa_100g,omitempty" csv:"cocoa_100g"`
	Code                                            string `json:"code,omitempty" csv:"code"`
	CollagenMeatProteinRatio100g                    string `json:"collagen-meat-protein-ratio_100g,omitempty" csv:"collagen-meat-protein-ratio_100g"`
	Completeness                                    string `json:"completeness,omitempty" csv:"completeness"`
	Copper100g                                      string `json:"copper_100g,omitempty" csv:"copper_100g"`
	Countries                                       string `json:"countries,omitempty" csv:"countries"`
	CountriesEn                                     string `json:"countries_en,omitempty" csv:"countries_en"`
	CountriesTags                                   string `json:"countries_tags,omitempty" csv:"countries_tags"`
	CreatedDatetime                                 string `json:"created_datetime,omitempty" csv:"created_datetime"`
	CreatedT                                        string `json:"created_t,omitempty" csv:"created_t"`
	Creator                                         string `json:"creator,omitempty" csv:"creator"`
	DataQualityErrorsTags                           string `json:"data_quality_errors_tags,omitempty" csv:"data_quality_errors_tags"`
	DihomoGammaLinolenicAcid100g                    string `json:"dihomo-gamma-linolenic-acid_100g,omitempty" csv:"dihomo-gamma-linolenic-acid_100g"`
	DocosahexaenoicAcid100g                         string `json:"docosahexaenoic-acid_100g,omitempty" csv:"docosahexaenoic-acid_100g"`
	EcoscoreGrade                                   string `json:"ecoscore_grade,omitempty" csv:"ecoscore_grade"`
	EcoscoreScore                                   string `json:"ecoscore_score,omitempty" csv:"ecoscore_score"`
	EicosapentaenoicAcid100g                        string `json:"eicosapentaenoic-acid_100g,omitempty" csv:"eicosapentaenoic-acid_100g"`
	ElaidicAcid100g                                 string `json:"elaidic-acid_100g,omitempty" csv:"elaidic-acid_100g"`
	EmbCodes                                        string `json:"emb_codes,omitempty" csv:"emb_codes"`
	EmbCodesTags                                    string `json:"emb_codes_tags,omitempty" csv:"emb_codes_tags"`
	EnergyFromFat100g                               string `json:"energy-from-fat_100g,omitempty" csv:"energy-from-fat_100g"`
	EnergyKcal100g                                  string `json:"energy-kcal_100g,omitempty" csv:"energy-kcal_100g"`
	EnergyKj100g                                    string `json:"energy-kj_100g,omitempty" csv:"energy-kj_100g"`
	Energy100g                                      string `json:"energy_100g,omitempty" csv:"energy_100g"`
	ErucicAcid100g                                  string `json:"erucic-acid_100g,omitempty" csv:"erucic-acid_100g"`
	Erythritol100g                                  string `json:"erythritol_100g,omitempty" csv:"erythritol_100g"`
	Fat100g                                         string `json:"fat_100g,omitempty" csv:"fat_100g"`
	Fiber100g                                       string `json:"fiber_100g,omitempty" csv:"fiber_100g"`
	FirstPackagingCodeGeo                           string `json:"first_packaging_code_geo,omitempty" csv:"first_packaging_code_geo"`
	Fluoride100g                                    string `json:"fluoride_100g,omitempty" csv:"fluoride_100g"`
	Folates100g                                     string `json:"folates_100g,omitempty" csv:"folates_100g"`
	FoodGroups                                      string `json:"food_groups,omitempty" csv:"food_groups"`
	FoodGroupsEn                                    string `json:"food_groups_en,omitempty" csv:"food_groups_en"`
	FoodGroupsTags                                  string `json:"food_groups_tags,omitempty" csv:"food_groups_tags"`
	Fructose100g                                    string `json:"fructose_100g,omitempty" csv:"fructose_100g"`
	FruitsVegetablesNutsDried100g                   string `json:"fruits-vegetables-nuts-dried_100g,omitempty" csv:"fruits-vegetables-nuts-dried_100g"`
	FruitsVegetablesNutsEstimateFromIngredients100g string `json:"fruits-vegetables-nuts-estimate-from-ingredients_100g,omitempty" csv:"fruits-vegetables-nuts-estimate-from-ingredients_100g"`
	FruitsVegetablesNutsEstimate100g                string `json:"fruits-vegetables-nuts-estimate_100g,omitempty" csv:"fruits-vegetables-nuts-estimate_100g"`
	FruitsVegetablesNuts100g                        string `json:"fruits-vegetables-nuts_100g,omitempty" csv:"fruits-vegetables-nuts_100g"`
	GammaLinolenicAcid100g                          string `json:"gamma-linolenic-acid_100g,omitempty" csv:"gamma-linolenic-acid_100g"`
	GenericName                                     string `json:"generic_name,omitempty" csv:"generic_name"`
	Glucose100g                                     string `json:"glucose_100g,omitempty" csv:"glucose_100g"`
	GlycemicIndex100g                               string `json:"glycemic-index_100g,omitempty" csv:"glycemic-index_100g"`
	GondoicAcid100g                                 string `json:"gondoic-acid_100g,omitempty" csv:"gondoic-acid_100g"`
	ImageIngredientsSmallURL                        string `json:"image_ingredients_small_url,omitempty" csv:"image_ingredients_small_url"`
	ImageIngredientsURL                             string `json:"image_ingredients_url,omitempty" csv:"image_ingredients_url"`
	ImageNutritionSmallURL                          string `json:"image_nutrition_small_url,omitempty" csv:"image_nutrition_small_url"`
	ImageNutritionURL                               string `json:"image_nutrition_url,omitempty" csv:"image_nutrition_url"`
	ImageSmallURL                                   string `json:"image_small_url,omitempty" csv:"image_small_url"`
	ImageURL                                        string `json:"image_url,omitempty" csv:"image_url"`
	IngredientsAnalysisTags                         string `json:"ingredients_analysis_tags,omitempty" csv:"ingredients_analysis_tags"`
	IngredientsTags                                 string `json:"ingredients_tags,omitempty" csv:"ingredients_tags"`
	IngredientsText                                 string `json:"ingredients_text,omitempty" csv:"ingredients_text"`
	Inositol100g                                    string `json:"inositol_100g,omitempty" csv:"inositol_100g"`
	InsolubleFiber100g                              string `json:"insoluble-fiber_100g,omitempty" csv:"insoluble-fiber_100g"`
	Iodine100g                                      string `json:"iodine_100g,omitempty" csv:"iodine_100g"`
	Iron100g                                        string `json:"iron_100g,omitempty" csv:"iron_100g"`
	Labels                                          string `json:"labels,omitempty" csv:"labels"`
	LabelsEn                                        string `json:"labels_en,omitempty" csv:"labels_en"`
	LabelsTags                                      string `json:"labels_tags,omitempty" csv:"labels_tags"`
	Lactose100g                                     string `json:"lactose_100g,omitempty" csv:"lactose_100g"`
	LastImageDatetime                               string `json:"last_image_datetime,omitempty" csv:"last_image_datetime"`
	LastImageT                                      string `json:"last_image_t,omitempty" csv:"last_image_t"`
	LastModifiedBy                                  string `json:"last_modified_by,omitempty" csv:"last_modified_by"`
	LastModifiedDatetime                            string `json:"last_modified_datetime,omitempty" csv:"last_modified_datetime"`
	LastModifiedT                                   string `json:"last_modified_t,omitempty" csv:"last_modified_t"`
	LastUpdatedDatetime                             string `json:"last_updated_datetime,omitempty" csv:"last_updated_datetime"`
	LastUpdatedT                                    string `json:"last_updated_t,omitempty" csv:"last_updated_t"`
	LauricAcid100g                                  string `json:"lauric-acid_100g,omitempty" csv:"lauric-acid_100g"`
	LignocericAcid100g                              string `json:"lignoceric-acid_100g,omitempty" csv:"lignoceric-acid_100g"`
	LinoleicAcid100g                                string `json:"linoleic-acid_100g,omitempty" csv:"linoleic-acid_100g"`
	Magnesium100g                                   string `json:"magnesium_100g,omitempty" csv:"magnesium_100g"`
	MainCategory                                    string `json:"main_category,omitempty" csv:"main_category"`
	MainCategoryEn                                  string `json:"main_category_en,omitempty" csv:"main_category_en"`
	Maltodextrins100g                               string `json:"maltodextrins_100g,omitempty" csv:"maltodextrins_100g"`
	Maltose100g                                     string `json:"maltose_100g,omitempty" csv:"maltose_100g"`
	Manganese100g                                   string `json:"manganese_100g,omitempty" csv:"manganese_100g"`
	ManufacturingPlaces                             string `json:"manufacturing_places,omitempty" csv:"manufacturing_places"`
	ManufacturingPlacesTags                         string `json:"manufacturing_places_tags,omitempty" csv:"manufacturing_places_tags"`
	MeadAcid100g                                    string `json:"mead-acid_100g,omitempty" csv:"mead-acid_100g"`
	MelissicAcid100g                                string `json:"melissic-acid_100g,omitempty" csv:"melissic-acid_100g"`
	Molybdenum100g                                  string `json:"molybdenum_100g,omitempty" csv:"molybdenum_100g"`
	MonounsaturatedFat100g                          string `json:"monounsaturated-fat_100g,omitempty" csv:"monounsaturated-fat_100g"`
	MontanicAcid100g                                string `json:"montanic-acid_100g,omitempty" csv:"montanic-acid_100g"`
	MyristicAcid100g                                string `json:"myristic-acid_100g,omitempty" csv:"myristic-acid_100g"`
	NervonicAcid100g                                string `json:"nervonic-acid_100g,omitempty" csv:"nervonic-acid_100g"`
	Nitrate100g                                     string `json:"nitrate_100g,omitempty" csv:"nitrate_100g"`
	NoNutritionData                                 string `json:"no_nutrition_data,omitempty" csv:"no_nutrition_data"`
	NovaGroup                                       string `json:"nova_group,omitempty" csv:"nova_group"`
	Nucleotides100g                                 string `json:"nucleotides_100g,omitempty" csv:"nucleotides_100g"`
	NutrientLevelsTags                              string `json:"nutrient_levels_tags,omitempty" csv:"nutrient_levels_tags"`
	NutriscoreGrade                                 string `json:"nutriscore_grade,omitempty" csv:"nutriscore_grade"`
	NutriscoreScore                                 string `json:"nutriscore_score,omitempty" csv:"nutriscore_score"`
	NutritionScoreFr100g                            string `json:"nutrition-score-fr_100g,omitempty" csv:"nutrition-score-fr_100g"`
	NutritionScoreUk100g                            string `json:"nutrition-score-uk_100g,omitempty" csv:"nutrition-score-uk_100g"`
	OleicAcid100g                                   string `json:"oleic-acid_100g,omitempty" csv:"oleic-acid_100g"`
	Omega3Fat100g                                   string `json:"omega-3-fat_100g,omitempty" csv:"omega-3-fat_100g"`
	Omega6Fat100g                                   string `json:"omega-6-fat_100g,omitempty" csv:"omega-6-fat_100g"`
	Omega9Fat100g                                   string `json:"omega-9-fat_100g,omitempty" csv:"omega-9-fat_100g"`
	Origins                                         string `json:"origins,omitempty" csv:"origins"`
	OriginsEn                                       string `json:"origins_en,omitempty" csv:"origins_en"`
	OriginsTags                                     string `json:"origins_tags,omitempty" csv:"origins_tags"`
	Owner                                           string `json:"owner,omitempty" csv:"owner"`
	Packaging                                       string `json:"packaging,omitempty" csv:"packaging"`
	PackagingEn                                     string `json:"packaging_en,omitempty" csv:"packaging_en"`
	PackagingTags                                   string `json:"packaging_tags,omitempty" csv:"packaging_tags"`
	PackagingText                                   string `json:"packaging_text,omitempty" csv:"packaging_text"`
	PalmiticAcid100g                                string `json:"palmitic-acid_100g,omitempty" csv:"palmitic-acid_100g"`
	PantothenicAcid100g                             string `json:"pantothenic-acid_100g,omitempty" csv:"pantothenic-acid_100g"`
	Ph100g                                          string `json:"ph_100g,omitempty" csv:"ph_100g"`
	Phosphorus100g                                  string `json:"phosphorus_100g,omitempty" csv:"phosphorus_100g"`
	Phylloquinone100g                               string `json:"phylloquinone_100g,omitempty" csv:"phylloquinone_100g"`
	PnnsGroups1                                     string `json:"pnns_groups_1,omitempty" csv:"pnns_groups_1"`
	PnnsGroups2                                     string `json:"pnns_groups_2,omitempty" csv:"pnns_groups_2"`
	Polyols100g                                     string `json:"polyols_100g,omitempty" csv:"polyols_100g"`
	PolyunsaturatedFat100g                          string `json:"polyunsaturated-fat_100g,omitempty" csv:"polyunsaturated-fat_100g"`
	PopularityTags                                  string `json:"popularity_tags,omitempty" csv:"popularity_tags"`
	Potassium100g                                   string `json:"potassium_100g,omitempty" csv:"potassium_100g"`
	ProductName                                     string `json:"product_name,omitempty" csv:"product_name"`
	ProductQuantity                                 string `json:"product_quantity,omitempty" csv:"product_quantity"`
	Proteins100g                                    string `json:"proteins_100g,omitempty" csv:"proteins_100g"`
	PurchasePlaces                                  string `json:"purchase_places,omitempty" csv:"purchase_places"`
	Quantity                                        string `json:"quantity,omitempty" csv:"quantity"`
	Salt100g                                        string `json:"salt_100g,omitempty" csv:"salt_100g"`
	SaturatedFat100g                                string `json:"saturated-fat_100g,omitempty" csv:"saturated-fat_100g"`
	Selenium100g                                    string `json:"selenium_100g,omitempty" csv:"selenium_100g"`
	SerumProteins100g                               string `json:"serum-proteins_100g,omitempty" csv:"serum-proteins_100g"`
	ServingQuantity                                 string `json:"serving_quantity,omitempty" csv:"serving_quantity"`
	ServingSize                                     string `json:"serving_size,omitempty" csv:"serving_size"`
	Silica100g                                      string `json:"silica_100g,omitempty" csv:"silica_100g"`
	Sodium100g                                      string `json:"sodium_100g,omitempty" csv:"sodium_100g"`
	SolubleFiber100g                                string `json:"soluble-fiber_100g,omitempty" csv:"soluble-fiber_100g"`
	Starch100g                                      string `json:"starch_100g,omitempty" csv:"starch_100g"`
	States                                          string `json:"states,omitempty" csv:"states"`
	StatesEn                                        string `json:"states_en,omitempty" csv:"states_en"`
	StatesTags                                      string `json:"states_tags,omitempty" csv:"states_tags"`
	StearicAcid100g                                 string `json:"stearic-acid_100g,omitempty" csv:"stearic-acid_100g"`
	Stores                                          string `json:"stores,omitempty" csv:"stores"`
	Sucrose100g                                     string `json:"sucrose_100g,omitempty" csv:"sucrose_100g"`
	Sugars100g                                      string `json:"sugars_100g,omitempty" csv:"sugars_100g"`
	Sulphate100g                                    string `json:"sulphate_100g,omitempty" csv:"sulphate_100g"`
	Taurine100g                                     string `json:"taurine_100g,omitempty" csv:"taurine_100g"`
	Traces                                          string `json:"traces,omitempty" csv:"traces"`
	TracesEn                                        string `json:"traces_en,omitempty" csv:"traces_en"`
	TracesTags                                      string `json:"traces_tags,omitempty" csv:"traces_tags"`
	TransFat100g                                    string `json:"trans-fat_100g,omitempty" csv:"trans-fat_100g"`
	UniqueScansN                                    string `json:"unique_scans_n,omitempty" csv:"unique_scans_n"`
	UnsaturatedFat100g                              string `json:"unsaturated-fat_100g,omitempty" csv:"unsaturated-fat_100g"`
	URL                                             string `json:"url,omitempty" csv:"url"`
	VitaminA100g                                    string `json:"vitamin-a_100g,omitempty" csv:"vitamin-a_100g"`
	VitaminB12100g                                  string `json:"vitamin-b12_100g,omitempty" csv:"vitamin-b12_100g"`
	VitaminB1100g                                   string `json:"vitamin-b1_100g,omitempty" csv:"vitamin-b1_100g"`
	VitaminB2100g                                   string `json:"vitamin-b2_100g,omitempty" csv:"vitamin-b2_100g"`
	VitaminB6100g                                   string `json:"vitamin-b6_100g,omitempty" csv:"vitamin-b6_100g"`
	VitaminB9100g                                   string `json:"vitamin-b9_100g,omitempty" csv:"vitamin-b9_100g"`
	VitaminC100g                                    string `json:"vitamin-c_100g,omitempty" csv:"vitamin-c_100g"`
	VitaminD100g                                    string `json:"vitamin-d_100g,omitempty" csv:"vitamin-d_100g"`
	VitaminE100g                                    string `json:"vitamin-e_100g,omitempty" csv:"vitamin-e_100g"`
	VitaminK100g                                    string `json:"vitamin-k_100g,omitempty" csv:"vitamin-k_100g"`
	VitaminPp100g                                   string `json:"vitamin-pp_100g,omitempty" csv:"vitamin-pp_100g"`
	WaterHardness100g                               string `json:"water-hardness_100g,omitempty" csv:"water-hardness_100g"`
	Zinc100g                                        string `json:"zinc_100g,omitempty" csv:"zinc_100g"`
}

func (off OpenFoodFactCSVEntry) GetID() string {
	return off.ID
}

func (off *OpenFoodFactCSVEntry) SetID(id string) {
	off.ID = id
}
