services:
  ####### MongoDB #######
  mongo:
    image: mongo:6
    networks:
      factsfood:
    restart: always
    volumes:
      - ./data/db:/data/db
    command: --wiredTigerCacheSizeGB 0.25
  ####### Migration #######
  migrations:
    image: nbittich/mongodb-migration:v0.1.1
    restart: "no"
    volumes:
      - ./config/migrations:/migrations
    networks:
      factsfood:

networks:
  factsfood:
